export const MOCK_DATA = [
  {
    'date sent': 'date sent',
    desc: 'desc',
    from: 'from',
    id: '1',
    pdf: 'pdf',
    'time sent': 'time sent',
    type: 'type',
  },
  {
    'date sent': 'date sent',
    desc: 'desc',
    from: 'from',
    id: '2',
    pdf: 'pdf',
    'time sent': 'time sent',
    type: 'type',
  },
  {
    'date sent': 'date sent',
    desc: 'desc',
    from: 'from',
    id: '3',
    pdf: 'pdf',
    'time sent': 'time sent',
    type: 'type',
  },
  {
    'date sent': 'date sent',
    desc: 'desc',
    from: 'from',
    id: '4',
    pdf: 'pdf',
    'time sent': 'time sent',
    type: 'type',
  },
  {
    'date sent': 'date sent',
    desc: 'desc',
    from: 'from',
    id: '5',
    pdf: 'pdf',
    'time sent': 'time sent',
    type: 'type',
  },
];

export const MOCK_HEADERS = [
  'date sent',
  'time sent',
  'type',
  'from',
  'desc',
  'pdf',
];
