export const FETCH_PAYMENTS_DATA = 'app/Payments/FETCH_PAYMENTS_DATA';
export const FETCH_PAYMENTS_DATA_FAILURE =
  'app/Payments/FETCH_PAYMENTS_DATA_FAILURE';
export const FETCH_PAYMENTS_DATA_SUCCESS =
  'app/Payments/FETCH_PAYMENTS_DATA_SUCCESS';
