export const CLEAR_LIST_MODAL_DATA = 'app/Main/CLEAR_LIST_MODAL_DATA';
export const FETCH_LOAN_DATA = 'app/Main/FETCH_LOAN_DATA';
export const FETCH_LOAN_DATA_FAILURE = 'app/Main/FETCH_LOAN_DATA_FAILURE';
export const FETCH_LOAN_DATA_SUCCESS = 'app/Main/FETCH_LOAN_DATA_SUCCESS';
export const SET_AUDIO_MODAL_DATA = 'app/Main/SET_AUDIO_MODAL_DATA';
export const SET_DOWNLOAD_MODAL_DATA = 'app/Main/SET_DOWNLOAD_MODAL_DATA';
