const initialState = {
  audioModalData: {},
  downloadModalData: {},
  error: false,
  loading: false,
  loanData: {
    balances: {
      advance: 0,
      deficit: 0,
      discBal: 0,
      escrow: 0,
      hud: 0,
      interestDue: 0,
      lateChargeDue: 0,
      originalDisbursement: 0,
      originalLoan: 0,
      replacementReserve: 0,
      resEsc: 0,
      suspense: 0,
    },
    borrower: {
      city: '',
      email: '',
      name: '',
      phone: '',
      ssn: '',
      state: '',
      streetAddressA: '',
      streetAddressB: '',
      unit: '',
      zip: '',
    },
    coBorrower: {
      city: '',
      email: '',
      name: '',
      phone: '',
      ssn: '',
      state: '',
      streetAddressA: '',
      streetAddressB: '',
      unit: '',
      zip: '',
    },
    escrow: {
      analysisDate: '',
      balance: 0,
      currentDueDate: '',
      currentPayment: 0,
      effectiveDueDate: '',
      effectivePayment: 0,
    },
    homeownersHazard: [],
    mortgage: [],
    pastHomeownersHazard: [],
    pastMortgage: [],
    pastTaxes: [],
    payment: {
      accidentAndHealth: 0,
      bsc: 0,
      escrow: 0,
      hudP: 0,
      lifeInsurance: 0,
      miscellaneous: 0,
      netPayment: 0,
      paymentFrequency: 0,
      principalAndInterest1: 0,
      principalAndInterest2: 0,
      replacementReserve: 0,
      total: 0,
    },
    property: {
      city: '',
      resident: '',
      state: '',
      streetAddressA: '',
      streetAddressB: '',
      unit: '',
      zip: '',
    },
    recentCalls: [],
    recentDocuments: [],
    recentPayments: [],
    stops: [],
    summaries: {
      calls: {
        avgCallsQuarter: 0,
        avgTimeCall: 0,
        callsLast30Days: 0,
        mostFreqReason: '',
        totalCalls: 0,
        totalNotes: 0,
      },
      loan: {
        assumptionCode: '',
        assumptionDate: '',
        graceDays: 0,
        health: 0,
        interestRate: 0,
        investorCode: '',
        investorName: '',
        lienPosition: '',
        loanType: '',
        maturityDate: '',
        originalLoanAmount: 0,
        originationDate: '',
        principalBalance: 0,
        status: '',
      },
      payment: {
        badCheckFees: 0,
        dueDate: '',
        lateChargesDue: 0,
        otherFees: 0,
        paymentDue: 0,
        totalDue: 0,
      },
      service: {
        eStatements: '',
        webAccess: '',
        welcomeCall: '',
      },
    },
    taxes: [],
  },
  loanNumber: '',
};

export default initialState;
