export const sidebarSummaryData = {
  callsSummaryData: [
    { label: 'Total Calls', value: '82' },
    { label: 'Total Notes', value: '27' },
    { label: 'Average Calls/Quarter', value: '4' },
    { label: 'Calls/Last 30 Days', value: '3' },
    { label: 'Average Time/Call', value: '3 min' },
    { label: 'Most Frequent Reason', value: 'A100' },
  ],
  loanSummaryData: [
    { label: 'Loan Type', value: 'FHA Residential' },
    { label: 'Status', value: 'Current' },
    { label: 'Principal Balance', value: '$234,456.78' },
    { label: 'Original Loan Amount', value: '$345,567,89' },
    { label: 'Investor Name', value: 'Nevada Housing' },
    { label: 'Investor Code', value: 'N03' },
    { label: 'Assumption Code', value: 'A' },
    { label: 'Assumption Date', value: '2/3/2020' },
    { label: 'Interest Rate', value: '5%' },
    { label: 'Origination Date', value: '5/6/2012' },
    { label: 'Maturity Date', value: '5/6/2042' },
    { label: 'Grace Days', value: '15' },
    { label: 'Lien Position', value: '1st Mortgage' },
  ],
  paymentSummaryData: [
    { label: 'Payment Due', value: '$2,345.67' },
    { label: 'Late Charges Due', value: '$0.00' },
    { label: 'Bad Check Fees', value: '$0.00' },
    { label: 'Other Fees', value: '$123.45' },
    { label: 'Total Due', value: '$2,469.12' },
    { label: 'Due Date', value: '8/1/2020' },
  ],
  serviceSummaryData: [
    { label: 'E-Statements', value: 'Yes' },
    { label: 'Web Access', value: 'Registered' },
    { label: 'Welcome Call', value: 'Yes' },
  ],
};
