export const FETCH_CALLS_DATA = 'app/Calls/FETCH_CALLS_DATA';
export const FETCH_CALLS_DATA_FAILURE = 'app/Calls/FETCH_CALLS_DATA_FAILURE';
export const FETCH_CALLS_DATA_SUCCESS = 'app/Calls/FETCH_CALLS_DATA_SUCCESS';
export const SET_IS_FILTERED = 'app/Calls/SET_IS_FILTERED';
export const SET_LOADING_TRUE = 'app/Calls/SET_LOADING_TRUE';
