export const FETCH_DOCUMENTS_DATA = 'app/Documents/FETCH_DOCUMENTS_DATA';
export const FETCH_DOCUMENTS_DATA_FAILURE =
  'app/Documents/FETCH_DOCUMENTS_DATA_FAILURE';
export const FETCH_DOCUMENTS_DATA_SUCCESS =
  'app/Documents/FETCH_DOCUMENTS_DATA_SUCCESS';
export const ON_UNMOUNT = 'app/Documents/ON_UNMOUNT';
